blog_book/auth/urls.py
from django.urls import path
from .views import login_view, register_view, logout_view

app_name = "auth"

urlpatterns = [
  path("login", login_view, name="login"),
  path("register", register_view, name="register"),
  path("logout", logout_view, name="logout")
]

blog_book/blog_book/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view, feed_view

urlpatterns = [
    path('', home_view, name='index'),
    path('feed/', feed_view, name='feed_view'),
    path('admin/', admin.site.urls),
    path('auth/', include('auth.urls')),
    path('blogs/', include('blogs.urls')),
    path('posts/', include('posts.urls')),
]

blog_book/blogs/urls.py
from django.urls import path
from .views import * 

app_name="blogs"

urlpatterns = [
  path('', index, name='index'),
  path('<int:blog_id>/', blog_view, name='blog_view'),
  path('new/', blog_create, name='blog_create'),
  path('<int:blog_id>/edit/',blog_edit,name='blog_edit'),
  path('<int:blog_id>/posts/new/', post_create, name='post_create'),
  path('<int:blog_id>/followers/', blog_follower, name='blog_follower')
]

blog_book/templates/partials/flash.html
  {% if messages %}
    {% for message in messages %}
        {% if message and message.tags == "error" %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
            </button>
        </div>
        {% elif message and message.tags == "success" %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
            </button>
        </div>
        {% endif %}
    {% endfor %}
  {% endif %} 

blog_book/templates/partials/header.html
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">Blog Book</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
              <a class="nav-link" href="{% url 'feed_view' %}">Feed</a>
              <a class="nav-link" href="{% url 'blogs:index' %}">Blogs</a>
              <a class="nav-link" href="{% url 'blogs:blog_create' %}">New Blog</a>
          </div>
          <div class="navbar-nav ms-auto">
              {% if not request.user.is_authenticated %}
              <a class="nav-link" href="{% url 'auth:login' %}">Login</a>
              <a class="nav-link" href="{% url 'auth:register' %}">Register</a>
              {% else %}
              <a class="nav-link" href="{% url 'auth:logout' %}">Logout</a>
              {% endif %}
          </div>
      </div>
  </div>
</nav>