blog_book/auth/urls.py
from django.urls import path
from .views import login_view, register_view, logout_view

app_name = "auth"

urlpatterns = [
  path("login", login_view, name="login"),
  path("register", register_view, name="register"),
  path("logout", logout_view, name="logout")
]

blog_book/blog_book/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view, feed_view

urlpatterns = [
    path('', home_view, name='index'),
    path('feed/', feed_view, name='feed_view'),
    path('admin/', admin.site.urls),
    path('auth/', include('auth.urls')),
    path('blogs/', include('blogs.urls')),
    path('posts/', include('posts.urls')),
]

blog_book/blogs/urls.py
from django.urls import path
from .views import * 

app_name="blogs"

urlpatterns = [
  path('', index, name='index'),
  path('<int:blog_id>/', blog_view, name='blog_view'),
  path('new/', blog_create, name='blog_create'),
  path('<int:blog_id>/edit/',blog_edit,name='blog_edit'),
  path('<int:blog_id>/posts/new/', post_create, name='post_create'),
  path('<int:blog_id>/followers/', blog_follower, name='blog_follower')
]

blog_book/posts/urls.py
from django.urls import path
from .views import * 

app_name="posts"

urlpatterns = [
  # path('', index, name='index'),
  path('<int:post_id>/', post_view, name='post_view'),
  path('<int:post_id>/edit/', post_edit, name="post_edit"),
  path('<int:post_id>/comments/', comment_create, name='comment_create'),
  path('<int:post_id>/comments/<int:comment_id>/', comment_delete, name='comment_delete'),
]

blog_book/blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from markdown import markdown
from bleach import clean
from bleach_allowlist import markdown_tags, all_styles

markdown_attrs = {
    "*": ["id", "height", "width", "align", "border", "color", "margin", "padding"],
    "img": ["src", "alt", "title"],
    "a": ["href", "alt", "title"],
}

# Create your models here.
class Blog(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  title = models.CharField(max_length=30)
  description = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  followers = models.ManyToManyField(User, related_name="following")

  def __str__(self):
    return f"{self.title} - {self.user}"

class Post(models.Model):
  body = models.TextField()
  title = models.CharField(max_length=30)
  blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="posts")
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return f"{self.title} - {self.blog}"

  @property
  def html(self):
    uncleaned_html = markdown(self.body)
    cleaned_html = clean(uncleaned_html, markdown_tags, markdown_attrs, all_styles)
    return cleaned_html

class Comment(models.Model):
  text = models.TextField(max_length=200)
  user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
  post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return f"{self.user} - {self.post} - {self.created_at}"

blog_book/posts/models.py
from django.db import models

# Create your models here.

blog_book/blogs/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods, require_POST, require_GET
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from blogs.models import Blog, Post
from django import forms

class BlogCreationForm(forms.ModelForm):
  title = forms.CharField(max_length=30, label="Title", required=True,widget=forms.TextInput(attrs={'class': "form-control"}))
  description = forms.CharField(max_length=500, label='Description',required=True,widget=forms.Textarea(attrs={'class': 'form-control'}))
  class Meta:
    model = Blog
    fields = ['title', 'description']

class BlogEditForm(forms.ModelForm):
  title = forms.CharField(max_length=40, label="Title", required=True,widget=forms.TextInput(attrs={'class': "form-control"}))
  description = forms.CharField(max_length=500, label='Description',required=True,widget=forms.Textarea(attrs={'class': 'form-control'}))
  class Meta:
    model = Blog
    fields = ['title', 'description']

class PostCreationForm(forms.ModelForm):
  title = forms.CharField(max_length=40, label="Title", required=True,widget=forms.TextInput(attrs={'class': "form-control"}))
  body = forms.CharField(label='Body',required=True,widget=forms.Textarea(attrs={'class': 'form-control'}))
  class Meta:
    model = Post
    fields = ['title', 'body']

# Create your views here.
@require_GET
def index(request):
  blogs = Blog.objects.all()
  return render(request, 'index.html', {'blogs': blogs})

@require_GET
def blog_view(request, blog_id):
  blog = Blog.objects.get(pk=blog_id)
  posts = blog.posts.all()
  following = False
  if request.user.is_authenticated:
    following = request.user.following.filter(pk=blog_id).exists()
  return render(request, 'blog_view.html', {'blog': blog, 'posts': posts, 'following': following})

@require_http_methods(['GET', 'POST'])
@login_required(login_url=reverse_lazy('auth:login'))
def blog_create(request):
  if request.method == 'POST':
    form = BlogCreationForm(request.POST)
    # print(form)
    if form.is_valid():
      blog = form.save(commit=False)
      blog.user = request.user
      blog.save()
      messages.add_message(request, messages.SUCCESS, "Your blog was created successfully")
      return redirect('blogs:blog_view', blog_id=blog.id)
    return render(request, 'blog_create.html', {'form': form})
  else:
    form = BlogCreationForm()
    return render(request, 'blog_create.html', {'form': form})

@require_http_methods(['GET', 'POST'])
@login_required(login_url=reverse_lazy('auth:login'))
def blog_edit(request,blog_id):
  # Check if user is the owner of the blog.
  blog=Blog.objects.get(id=blog_id)
  if(blog.user!=request.user):
    messages.add_message(request, messages.ERROR, "You do not have the permission to edit this blog.")
    return redirect('blogs:blog_view',blog_id=blog_id)
  
  if request.method == 'POST':
    form = BlogEditForm(request.POST,initial={'title': 'Aakanksha'})
    if form.is_valid():
      blog_data = form.save(commit=False)
      try:
        blog.title = blog_data.title
        blog.description = blog_data.description
        blog.save()
        messages.add_message(request, messages.SUCCESS, "Your blog was successfully edited.")
      except:
        return render(request, 'blog_edit.html', {'form': form})
      return redirect('blogs:blog_view',blog_id=blog_id)
    return render(request, 'blog_edit.html', {'form': form, 'blog': blog})
  else:
    form = BlogEditForm()
    return render(request, 'blog_edit.html', {'form': form, 'blog': blog})

@require_http_methods(['GET', 'POST'])
@login_required(login_url=reverse_lazy('auth:login'))
def post_create(request, blog_id):
  blog=Blog.objects.get(id=blog_id)
  if(blog.user!=request.user):
    messages.add_message(request, messages.ERROR, "You do not have the permission to create post on this blog.")
    return redirect('blogs:blog_view',blog_id=blog_id)

  if request.method == 'POST':
    form = PostCreationForm(request.POST)
    if form.is_valid():
      post = form.save(commit=False)
      post.blog = blog
      post.save()
      messages.add_message(request, messages.SUCCESS, "Your post was successfully created.")
      return redirect('posts:post_view', post_id=post.id)
    return render(request, 'post_create.html', {'form': form, 'blog': blog})
  else:
    form = PostCreationForm()
    return render(request, 'post_create.html', {'form': form, 'blog': blog})

@require_http_methods(['DELETE', 'POST'])
@login_required(login_url=reverse_lazy('auth:login'))
def blog_follower(request, blog_id):
  if request.method == 'POST':
    if not request.user.following.filter(pk=blog_id).exists():
      request.user.following.add(blog_id)
  elif request.method == 'DELETE':
    if request.user.following.filter(pk=blog_id).exists():
      request.user.following.remove(blog_id)
  return redirect('blogs:blog_view', blog_id=blog_id)

blog_book/posts/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from blogs.models import Post, Comment
from django import forms

class PostEditForm(forms.ModelForm):
  title = forms.CharField(max_length=40, label="Title", required=True,widget=forms.TextInput(attrs={'class': "form-control"}))
  body = forms.CharField(label='Body',required=True,widget=forms.Textarea(attrs={'class': 'form-control'}))
  class Meta:
    model = Post
    fields = ['title', 'body']

# Create your views here.
def post_view(request, post_id):
  post = Post.objects.get(pk=post_id)
  post_html = post.html
  return render(request, 'post_view.html', {'post': post, 'post_html': post_html})

@require_http_methods(['GET', 'POST'])
@login_required(login_url=reverse_lazy('auth:login'))
def post_edit(request,post_id):
  # Check if user is the owner of the blog.
  post=Post.objects.get(id=post_id)
  # print('hi',post.blog.user,request.user,request.method);
  if(post.blog.user!=request.user):
    messages.add_message(request, messages.ERROR, "You do not have the permission to edit this blog.")
    return redirect('posts:post_view',post_id=post_id)
  
  if request.method == 'POST':
    form = PostEditForm(request.POST,initial={'title': 'Aakanksha'})
    if form.is_valid():
      post_data = form.save(commit=False)
      try:
        post.title = post_data.title
        post.body = post_data.body
        # print(post_data)
        post.save()
        messages.add_message(request, messages.SUCCESS, "Your post was successfully edited.")
      except:
        messages.add_message(request, messages.ERROR, "An error occurred while editing the post.")
        return render(request, 'post_edit.html', {'form': form, 'post': post})
      return redirect('posts:post_view',post_id=post_id)
    return render(request, 'post_edit.html', {'form': form, 'post': post})
  else:
    form = PostEditForm({'title': post.title, 'body': post.body})
    return render(request, 'post_edit.html', {'form': form, 'post': post})

@require_POST
@login_required(login_url=reverse_lazy('auth:login'))
def comment_create(request, post_id):
  text = request.POST.get('text')
  comment = Comment.objects.create(post_id=post_id, text=text, user=request.user)
  comment.save()
  messages.add_message(request, messages.SUCCESS, "Comment created.")
  return redirect('posts:post_view', post_id=post_id)

@require_http_methods(['DELETE'])
@login_required(login_url=reverse_lazy('auth:login'))
def comment_delete(request, post_id, comment_id):
  comment = Comment.objects.get(id=comment_id)
  if request.method == 'DELETE':
    if request.user.id == comment.user.id:
      comment.delete()
      messages.add_message(request, messages.SUCCESS, "Comment deleted.")
    else:
      messages.add_message(request, messages.ERROR, "You cannot delete this comment.")
    return redirect('posts:post_view', post_id=post_id)

blog_book/blogs/templates/blog_create.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blogs:index' %}">Blogs</a></li>
    <li class="breadcrumb-item active" aria-current="page">Create Blog</li>
  </ol>
</nav>
{% endblock %}

{% block main %}
<h2>Create a Blog</h2>

<form id="blog-create-form" method="post" class="needs-validation" novalidate>
  {% csrf_token %} {% for field in form %}
  <label for="{{field.id_for_label}}" class="form-label">{{field.label}}</label>
  <div class="input-group">
    {{field}}

    <div class="valid-feedback w-100">Looks good!</div>
    <div class="invalid-feedback w-100">
      {% if field.errors %} {% for error in field.errors %} {{ error }}
      <br />
      {% endfor %} {% endif %}
    </div>
  </div>
  <br />
  {% endfor %}
  <button type="submit" class="btn btn-primary">Create Blog</button>
</form>
{% endblock main %}

blog_book/blogs/templates/blog_edit.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blogs:index' %}">Blogs</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blogs:blog_view' blog_id=blog.id %}">{{blog.title}}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Edit Blog</li>
  </ol>
</nav>
{% endblock %}

{% block main %}
<h2>Edit Blog '{{blog.title}}'</h2>

<form id="blog-edit-form" method="post" class="needs-validation" novalidate>
  {% csrf_token %} 
  <label class="form-label">Title</label>
  <div class="input-group">
    <input type="text" name="title" class="form-control" value="{{blog.title}}" maxlength="40" required="" id="id_title">
  </div>
  <br />
  <label class="form-label">Description</label>
  <div class="input-group">
    <textarea name="description" cols="40" rows="10" class="form-control" maxlength="500" required="" id="id_description">{{blog.description}}</textarea>
  </div>
  <br />
    <button type="submit" class="btn btn-primary">Edit Blog</button>
</form>
{% endblock main %}

blog_book/blogs/templates/blog_view.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blogs:index' %}">Blogs</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{blog.title}}</li>
  </ol>
</nav>
{% endblock %}

{% block main %}
<div class="d-flex align-items-center">
  <h2 class="me-auto">{{blog.title}}</h2>
  {% if not blog.user.id == request.user.id %}
    {% if not following %}
      <form action="{% url 'blogs:blog_follower' blog_id=blog.id %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-primary">Follow</button>
      </form>
    {% else %}
      {% load method_override %}
      <form action="{% url 'blogs:blog_follower' blog_id=blog.id %}" method="POST">
        {% csrf_token %}
        {% method_override 'DELETE' %}
        <button type="submit" class="btn btn-primary">Unfollow</button>
      </form>
    {% endif %}
  {% else %}
    <a href="{% url 'blogs:blog_edit' blog_id=blog.id %}" class="btn btn-primary">Edit Blog</a>  
  {% endif %}

</div>

<p>{{blog.description}}</p>
<br />

<div class="d-flex align-items-center">
  <h2>Posts </h2>
  {% if blog.user.id == request.user.id %}
  <a href="{% url 'blogs:post_create' blog_id=blog.id %}" class="btn btn-primary ms-auto">Create Post</a>
  {% endif %}
</div>

  <div class="row">
    {% for post in posts %}
    <div class="mb-3 col col-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ post.title }}</h5>
          <p class="mb-2 card-subtitle text-muted">{{post.created_at}}</p>
          <a href="/posts/{{ post.id }}/" class="btn btn-primary">View Post</a>
        </div>
      </div>
    </div>
    {% empty %}
    <p class="fs-5 col-12">No posts yet.</p>
    {% endfor %}
  </div>
{% endblock %}

blog_book/blogs/templates/index.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Blogs</li>
  </ol>
</nav>
{% endblock %}

{% block main %}
<h2>View All Blogs</h2>

<div class="pt-3 mb-5">
  {% for blog in blogs %}
  <div class="mb-4 rounded-3 card">
    <div class="card-body">
      <a href="{% url 'blogs:blog_view' blog_id=blog.id %}">
        <h5 class="card-title">{{ blog.title }}</h5>
      </a>
      <h6 class="mb-2 card-subtitle text-muted">{{blog.user}} - {{blog.created_at}}</h6>
      <p class="card-text">{{blog.description }}</p>
    </div>
  </div>
  {% empty %}
  <p>There are no blogs.</p>
  {% endfor %}
</div>
{% endblock %}

blog_book/blogs/templates/post_create.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blogs:index' %}">Blogs</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blogs:blog_view' blog_id=blog.id %}">{{blog.title}}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Create Post</li>
  </ol>
</nav>
{% endblock %}

{% block main %}
<h2>Create a Post on <b>'{{blog.title}}'</b></h2>

<form id="post-create-form" method="post" class="needs-validation" novalidate>
  {% csrf_token %} {% for field in form %}
  <label for="{{field.id_for_label}}" class="form-label">{{field.label}}</label>
  <div class="input-group">
    {{field}}

    <div class="valid-feedback w-100">Looks good!</div>
    <div class="invalid-feedback w-100">
      {% if field.errors %} {% for error in field.errors %} {{ error }}
      <br />
      {% endfor %} {% endif %}
    </div>
  </div>
  <br />
  {% endfor %}
  <button type="submit" class="btn btn-primary">Create Post</button>
</form>
{% endblock main %}

blog_book/blogs/templates/post_edit.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blogs:index' %}">Blogs</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blogs:blog_view' blog_id=post.blog.id %}">{{post.blog.title}}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'posts:post_view' post_id=post.id %}">{{post.title}}</a></li>
    <li class="breadcrumb-item active" aria-current="page">Edit Post</li>
  </ol>
</nav>
{% endblock %}

{% block main %}
<h2>Edit a Post  <b>'{{post.title}}'</b></h2>

<form id="post-create-form" method="post" class="needs-validation" novalidate>
  {% csrf_token %} {% for field in form %}
  <label for="{{field.id_for_label}}" class="form-label">{{field.label}}</label>
  <div class="input-group">
    {{field}}

    <div class="valid-feedback w-100">Looks good!</div>
    <div class="invalid-feedback w-100">
      {% if field.errors %} {% for error in field.errors %} {{ error }}
      <br />
      {% endfor %} {% endif %}
    </div>
  </div>
  <br />
  {% endfor %}
  <button type="submit" class="btn btn-primary">Edit Post</button>
</form>
{% endblock main %}

blog_book/blogs/templates/post_view.html
{% extends 'base.html' %}

{% block breadcrumbs %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blogs:index' %}">Blogs</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blogs:blog_view' blog_id=post.blog.id %}">{{post.blog.title}}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{post.title}}</li>
  </ol>
</nav>
{% endblock %}

{% block main %}
<div class="row">

  <div class="col-md-6">
    <div class="d-flex align-items-center">
      <h2>{{post.title}}</h2>
      {% if post.blog.user.id == request.user.id %}
      <a href="{% url 'posts:post_edit' post_id=post.id %}" class="btn btn-primary ms-auto">Edit Post</a>
      {% endif %}
    </div>
    
    <br />
    <div class="p-4 border markdown-body border-gray rounded-3">
      {% autoescape off %}
      {{ post.html }}
      {% endautoescape %}
    </div>
  </div>

  <div class="col-md-6">
    <h2> Comments:</h2>
    <form action="{% url 'posts:comment_create' post_id=post.id %}" method="post" class="needs-validation" novalidate>
      {% csrf_token %}
      <div class="mb-3 input-group">
        <input id="comment-text" type="text" name="text" row="3" class="form-control" placeholder="Enter a comment" />
        <button type="submit" class="btn btn-primary">Add Comment</button>
      </div>
    </form>
    {% if not post.comments.all %}
    No Comments yet!!! <span class="fw-bold"> Add one!</span>
    
    {% else %}
      {% load method_override %}
      {% for comment in post.comments.all %}
      <div class="mb-3 card">
        <div class="card-body">
          <h5 class="card-title">{{comment.user}}</h5>
          <p class="card-text">{{comment.text}}</p>
          {% if request.user.id == comment.user.id %}
            <form action="{% url 'posts:comment_delete' post_id=post.id comment_id=comment.id %}" method="POST">
                {% csrf_token %}
                {% method_override 'DELETE' %}
                <button class="btn btn-sm btn-danger">Delete</button>
            </form>
          {% endif %}
        </div>
      </div>
      {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock %}